### ISSUE TITLE
ansible-validate-modules: command not found

### ISSUE THREAD

**Issue by krishnakothapalli** [relaxdiego/relaxdiego.github.com#1]
"Try running it with:
$ ansible-validate-modules lib/ansible/modules/core/cloud/amazon"

The above gave an error:
ubuntu:~/ansible$ ansible-validate-modules lib/ansible/modules/core/cloud/amazon
ansible-validate-modules: command not found

**Comment by relaxdiego** [comment]
Did you install it with: `pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing`

**Comment by relaxdiego** [comment]
BTW issue #3 suggests to use Python 2.7.8 or higher. Anything lower will cause the pip install to fail.

**Comment by gundalow** [comment]
Just in case anyone looks at this issue, the tool has been renamed and is included when you do a git clone of ansible.

You now invoke as:
`test/sanity/validate-modules/validate-modules lib/ansible/modules/core/cloud/amazon`

**Comment by relaxdiego** [comment]
Thanks for the reminder, @gundalow!
