### ISSUE TITLE
requirements.txt file doesn' t exist

### ISSUE THREAD

**Issue by cmoulliard** [relaxdiego/relaxdiego.github.com#14]
The requirements.txt file doesn' t exist anymore under this path with latest ansible project git cloned

```
pip install -r test/utils/tox/requirements.txt
```

**Comment by relaxdiego** [comment]
Thanks for the feedback, @cmoulliard! Were you able to find the new location? Would you be willing to submit a PR with the correction? You're free to add to the co-writers list along with that PR (e.g. https://github.com/relaxdiego/relaxdiego.github.com/commit/23274f0a9530848c876c848f6f252867ae2f937a#diff-afd8f92511cccd7a7320856c608fa095R7)

**Comment by relaxdiego** [comment]
@cmoulliard I went ahead and fixed the missing requirements.txt. Feel free to re-open this ticket if it still doesn't work for you. Thanks again for reporting this!
