### ISSUE TITLE
Text Defect: Mocking Objects in Python;  "2. In line 6"

### ISSUE THREAD

**Issue by sirvict0r** [relaxdiego/relaxdiego.github.com#18]
Description: Misspelling error in text.

2. In line 6, whe use the patch decorator to replace the memory address that my_package2.A points.

may be better:

2. In line 6, when we use the patch decorator to replace the memory address that my_package2.A points.

**Comment by relaxdiego** [comment]
This has been inadvertently fixed by a full rewrite I did a few months back. It now reads:

> Line 8: Using the patch decorator, we create an instance of Mock and make the variable `module2.A` point to this instance.
