### ISSUE TITLE
Update Writing Ansible Modules for Repo Merge?

### ISSUE THREAD

**Issue by ghost** [relaxdiego/relaxdiego.github.com#19]
Would it be possible to update your "writing ansible modules" posts to account for the repo merge?
I've spent the last day working through issues trying to get the nosetest in part two to work.

Of all the module unittesting tutorials, your's is by far the most accessible.

**Comment by relaxdiego** [comment]
Totally. Submit a PR and I’ll merge it.

**Comment by relaxdiego** [comment]
Closing due to OP deleting their account.
