### ISSUE TITLE
Unable to checkout '5ed887be9dda6eba58fd07092d5fbdc6b311bb48' in submodule path 

### ISSUE THREAD

**Issue by krishnakothapalli** [relaxdiego/relaxdiego.github.com#2]
I did "git push" in the submodule lib/ansible/modules/core and then "git push" of the ansible (both in iosxe_branch). Later I did pull request and merge in the github.

However when i do git clone --recursive, I get the error "Unable to checkout '5ed887be9dda6eba58fd07092d5fbdc6b311bb48' in submodule path 'lib/ansible/modules/core'"

Pls suggest the steps  to properly push, merge and clone 

ubuntu:~/junk$ git clone  https://github.com/krishnakothapalli/ansible.git --recursive
Cloning into 'ansible'...
remote: Counting objects: 122855, done.        
remote: Compressing objects: 100% (21/21), done.        
remote: Total 122855 (delta 8), reused 2 (delta 2), pack-reused 122830        
Receiving objects: 100% (122855/122855), 35.77 MiB | 1.36 MiB/s, done.
Resolving deltas: 100% (76068/76068), done.
Checking connectivity... done.
Submodule 'lib/ansible/modules/core' (https://github.com/ansible/ansible-modules-core) registered for path 'lib/ansible/modules/core'
Submodule 'lib/ansible/modules/extras' (https://github.com/ansible/ansible-modules-extras) registered for path 'lib/ansible/modules/extras'
Cloning into 'lib/ansible/modules/core'...
remote: Counting objects: 36650, done.        
remote: Compressing objects: 100% (18/18), done.        
remote: Total 36650 (delta 5), reused 2 (delta 2), pack-reused 36630        
Receiving objects: 100% (36650/36650), 8.71 MiB | 1.50 MiB/s, done.
Resolving deltas: 100% (24178/24178), done.
Checking connectivity... done.
fatal: reference is not a tree: 5ed887be9dda6eba58fd07092d5fbdc6b311bb48
Cloning into 'lib/ansible/modules/extras'...
remote: Counting objects: 33914, done.        
remote: Total 33914 (delta 0), reused 0 (delta 0), pack-reused 33913        
Receiving objects: 100% (33914/33914), 7.30 MiB | 1.48 MiB/s, done.
Resolving deltas: 100% (22657/22657), done.
Checking connectivity... done.
Submodule path 'lib/ansible/modules/extras': checked out '1c36665545ab3ceb7b5edb998a9b83eb8f6be133'
Unable to checkout '5ed887be9dda6eba58fd07092d5fbdc6b311bb48' in submodule path 'lib/ansible/modules/core'

**Comment by relaxdiego** [comment]
That means that sha 5ed887be9dda6eba58fd07092d5fbdc6b311bb48 is not merged to upstream ansible-modules-extras. do you have it in your fork of the repo? If you do, you should review the steps in "Prep Your Core (or Extras) Modules Repo"
