### ISSUE TITLE
RedactingFilter Issue

### ISSUE THREAD

**Issue by uenz** [relaxdiego/relaxdiego.github.com#21]
Hi,

i tried the redacting filter with python 2.7. The output file conttained the original string, not the redacted one.
After changing
`
    def filter(self, record):
        msg = self.redact(record.msg)
        if isinstance(record.args, dict):
            for k in record.args.keys():
                record.args[k] = self.redact(record.args[k])
        else:
            record.args = tuple(self.redact(arg) for arg in record.args)
        return True
`
to
`
    def filter(self, record):
        record.msg = self.redact(record.msg)
        if isinstance(record.args, dict):
            for k in record.args.keys():
                record.args[k] = self.redact(record.args[k])
        else:
            record.args = tuple(self.redact(arg) for arg in record.args)
        return True
`
the logfile was like expected.

**Comment by relaxdiego** [comment]
Thanks for providing the fix @uenz! Would you like to submit a patch so that it shows your name in the log? If not, I can do it myself no worries.

**Comment by uenz** [comment]
Hi,
thanks for responding. I try to provide a patch this evening.
Regards

**Comment by relaxdiego** [comment]
Thanks and no rush! Don’t forget to give yourself credit at tge top of the page right next to Hari Dara’s name. :-)

**Comment by relaxdiego** [comment]
Fixed by #22
