### ISSUE TITLE
issues i encountered while following steps

### ISSUE THREAD

**Issue by LambertoD** [relaxdiego/relaxdiego.github.com#3]
1. In **Install The Ansible Module Validator (Linter)** section:
Note that command `$ pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing` fails when ran with Python 2.7.5 version.   Upgrading to python 2.7.8 fixes the compile issue.

2. In **Now Let’s Actually Write Useful Code!** section:
a.  Small typo on line 23 `# Assert call to AsnibleModule`
b.  `def write_data(mod, data, dest):`  should be `def write_data(data, dest):` to make the test pass.  extra argument mod is causing test failure.

Other than above issues, i was able to replicate all expected results.
Excellent work on the walkthrough.

Thanks!

**Comment by relaxdiego** [comment]
Awesome! Thanks @LambertoD!
