### ISSUE TITLE
Ruby on Mac OSX does not balance as expected

### ISSUE THREAD

**Issue by TomFreudenberg** [relaxdiego/relaxdiego.github.com#30]
Hi Mark @relaxdiego 

thanks for your post of: https://relaxdiego.com/2017/02/load-balancing-sockets.html

But when running this on Mac OSX using HomeBrew rbenv and Ruby 3.0.3, I get this output:

```
Hello from 87732
Hello from 87732
Hello from 87733
Hello from 87733
Hello from 87733
Hello from 87733
Hello from 87733
Hello from 87731
Hello from 87731
Hello from 87731
```

Not really a balanced stack.

Any ideas what to change or add?

**Comment by TomFreudenberg** [comment]
I checked this also for rbenv ruby 2.6.9 and 2.7.5 - same - not balancing the sockets in any ordered way

**Comment by TomFreudenberg** [comment]
Running the same test on a Debian linux - the result is balanced as eexpected:

```
Hello from 14705
Hello from 14706
Hello from 14707
Hello from 14708
Hello from 14709
Hello from 14705
Hello from 14706
Hello from 14707
Hello from 14708
Hello from 14709
```

Strange behaviour on Mac OSX (Catalina)

**Comment by TomFreudenberg** [comment]
Running on a 8 Core Debian Linux and doing 1000 client calls while having 25 forks, the result list is not in a ordered manner anymore - but - still balanced:

Result

<img width="117" alt="image" src="https://user-images.githubusercontent.com/410087/189920015-e921bddc-3125-4c84-bd38-5f985bf6f52e.png">

Checked for balanced calls each pid

<img width="203" alt="image" src="https://user-images.githubusercontent.com/410087/189919863-65c449e3-63ac-4a4e-a6cc-ffead9d8bfe7.png">

**Comment by TomFreudenberg** [comment]
Same test on OSX Catalina will show unbalanced calls of the forked process pids

<img width="200" alt="image" src="https://user-images.githubusercontent.com/410087/189920936-ca12ea10-7af7-4dda-9d5b-4d2a63aa4818.png">

**Comment by relaxdiego** [comment]
Thanks for sharing your findings, @TomFreudenberg!

You have an interesting situation and I couldn't really find anything that properly explains it. For instance, the man page for socket(7) says this:

```
SO_REUSEPORT (since Linux 3.9)
For TCP sockets, this option allows accept(2) load
distribution in a multi-threaded server to be improved by
using a distinct listener socket for each thread.  This
provides improved load distribution as compared to
traditional techniques such using a single accept(2)ing
thread that distributes connections, or having multiple
threads that compete to accept(2) from the same socket.
```

Which doesn't say about the method of load distribution. I'm going to guess that the load balancing algorithm is entirely under the control of the kernel and it likely chooses what it deems to be the best one for a given case.

Alternatively, the above could just be a side effect of my sample code's children processes being effectively noops. Maybe you could try adding a sleep just before `connection.close` with a random sleep time to see if you get different results.

**Comment by TomFreudenberg** [comment]
Hi Mark @relaxdiego 

I also think that this is kernel (OS) related. From my current point of view, I guess the all (?) Linux systems work as expected - currently tested on Debian Buster, Ubuntu 22.04.

May BSD or Darwin goes its own way.

I also opened a question on StackOverflow: https://stackoverflow.com/questions/73704741/ruby-strange-forked-processes-behaviour-on-macos-vs-debian

Hopefully there will follow an explanation.

Cheers
Tom

**Comment by relaxdiego** [comment]
Thanks for sharing that SO link! I've just upvoted it. :)
