### ISSUE TITLE
Masking sensitive data in exceptions

### ISSUE THREAD

**Issue by donatogr** [relaxdiego/relaxdiego.github.com#32]
I'm trying to use filters to mask sensitive data in logs, as said here:
https://relaxdiego.com/2014/07/logging-in-python.html

But this doesn't cover the case in which we are logging exceptions via exc_info (e.g. using logger.exception).

Any easy solution for it?

Thx

**Comment by relaxdiego** [comment]
You got me there. :) I'm going to call on my co-authors for that article, @haridsv and @uenz, for help!

**Comment by uenz** [comment]
Hmm, had no need for it yet.But I think you can expand what’s described here:Logging exception filters in pythonstackoverflow.comWith the replacement/redacting filters from the article.Am 08.02.2023 um 11:51 schrieb Mark Maglana ***@***.***>:﻿
You got me there. :) I'm going to call on my co-authors for that article, @haridsv and @uenz, for help!
