### ISSUE TITLE
Preparing Your Environment 

### ISSUE THREAD

**Issue by peshay** [relaxdiego/relaxdiego.github.com#5]
> Prep Your Extras Modules Repo
There is no modules/extra and the repo itself is locked as everything now is merged in the main repository of ansible

**Comment by relaxdiego** [comment]
Thanks peshay! I've been meaning to update that series for some time now but just haven't found the time. Perhaps this is good motivation for me!

**Comment by peshay** [comment]
Thanks for that quick reply. Do you already have any other hints for me where I should prefer the original Ansible Documentation instead of your nice tutorial, as I'm currently trying to walk through it ;)

**Comment by relaxdiego** [comment]
I think I have a few links to the original docs but even that I'm not sure if it's still current.

**Comment by relaxdiego** [comment]
Closing this as per your PR #9. You rock!
