### ISSUE TITLE
no more modules submodule as of 12/2016

### ISSUE THREAD

**Issue by chbndrhnns** [relaxdiego/relaxdiego.github.com#8]
cf. https://docs.ansible.com/ansible/dev_guide/repomerge.html

Your manual reads like this:

`Prep Your Extras Modules Repo
Go to the extras modules subdir

$ cd lib/ansible/modules/extras
You are now in a git submodule.`

**Comment by relaxdiego** [comment]
Thanks for filing this, @chbndrhnns! This should be fixed by #9.
